### ISSUE TITLE
Fix L3 node in nitro-testnode

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/nitro-espresso-integration#159]
This is also required to run the E2E tests in nitro-contracts.

**Comment by ImJeremyHe** [comment]
espresso-sequencer is not designed to be used with the L2 chain, and we have other plans to support L3 nodes. However, I attempted to use espresso-sequencer with Nitro L2 anyway. It turned out that Nitro L2 nodes don't support finalized blocks, which are required for espresso-sequencer.

Therefore, we will stop fixing the L3 nodes for now and simply ignore the CI in nitro-contracts. I believe we've already conducted enough checks on the nitro-contracts in our end-to-end tests.
