### ISSUE TITLE
How to verify TEE signature in smart contract?

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/nitro-espresso-integration#287]
@alxiong did some research

Scheme is ECDSA.

Automata has implementation: https://github.com/automata-network/automata-dcap-attestation/blob/main/contracts/verifiers/V4QuoteVerifier.sol

Cost estimates in readme: https://github.com/automata-network/automata-dcap-attestation

**Comment by sveitser** [comment]
@alxiong just assigned you because you might be working on this. Feel free to drop a link here.

**Comment by Sneh1999** [comment]
Closing this issue because we have verified that we can use [automata contracts](https://github.com/automata-network/automata-dcap-attestation/blob/main/contracts/verifiers/V3QuoteVerifier.sol#L21) for verification

Created three issues for implementation:

https://github.com/EspressoSystems/nitro-espresso-integration/issues/311
https://github.com/EspressoSystems/nitro-espresso-integration/issues/312
https://github.com/EspressoSystems/nitro-espresso-integration/issues/313
